on:
  push:
    branches:
      - dev

name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get dev
      run:  git fetch origin dev
    - name: Movendo para diretorio de codigo
      run:  cd puma
    - name: Instalar dependencias
      run:  npm install
    - name: Instalar Jest
      run:  npm install -g jest
    - name: Executar testes
      run:  jest --coverage --runInBand --detectOpenHandles --forceExit
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
